### ISSUE TITLE
No repo Link 

### ISSUE THREAD

**Issue by gargi** [SoftwareEngineeringToolDemos/ICSE-2014-ImpactMiner#8]
The GitHub repository page should have a link to the original website after the description at the top.

**Comment by smalleni** [comment]
Here is the link to the [Original Project Page](http://www.cs.wm.edu/semeru/ImpactMiner/)
Does this not suffice?

**Comment by gargi** [comment]
Hi,
I have created this issue according to the following grading rubric point:
At the top of the page, is a project website filled in with a link to the original website? [link]

**Comment by smalleni** [comment]
I'm with you on this. Please create a pull request and submit it and I will be happy to merge ( as I said there are merge conflicts with your previous request, it would help if you could push the commits to a new branch).

**Comment by smalleni** [comment]
@gsrajadh your firrt pull request fixed nearly everything, you need to fix only 3 and now there appear to be 3 issues..can you put in a new pull request

**Comment by gargi** [comment]
Hi, actually I can't fix the project description and link thing as I told you. I tried forking and doing the changes but when I compare repos it doesn't show those changes. thats why I was planning to fix Fix for #3, #2, #5. Can you please go back to the previous commit?
